
export enum Keys {
	A = "KeyA",
	B = "KeyB",
	C = "KeyC",
	D = "KeyD",
	E = "KeyE",
	F = "KeyF",
	G = "KeyG",
	H = "KeyH",
	I = "KeyI",
	J = "KeyJ",
	K = "KeyK",
	L = "KeyL",
	M = "KeyM",
	N = "KeyN",
	O = "KeyO",
	P = "KeyP",
	Q = "KeyQ",
	R = "KeyR",
	S = "KeyS",
	T = "KeyT",
	U = "KeyU",
	V = "KeyV",
	W = "KeyW",
	X = "KeyX",
	Y = "KeyY",
	Z = "KeyZ",

	Digit1 = "Digit1",
	Digit2 = "Digit2",
	Digit3 = "Digit3",
	Digit4 = "Digit4",
	Digit5 = "Digit5",
	Digit6 = "Digit6",
	Digit7 = "Digit7",
	Digit8 = "Digit8",
	Digit9 = "Digit9",
	Digit0 = "Digit0",

	Numpad1 = "Numpad1",
	Numpad2 = "Numpad2",
	Numpad3 = "Numpad3",
	Numpad4 = "Numpad4",
	Numpad5 = "Numpad5",
	Numpad6 = "Numpad6",
	Numpad7 = "Numpad7",
	Numpad8 = "Numpad8",
	Numpad9 = "Numpad9",
	Numpad0 = "Numpad0",

	F1 = "F1",
	F2 = "F2",
	F3 = "F3",
	F4 = "F4",
	F5 = "F5",
	F6 = "F6",
	F7 = "F7",
	F8 = "F8",
	F9 = "F9",
	F10 = "F10",
	F11 = "F11",
	F12 = "F12",

	Esc = "Escape",
	Backquote = "Backquote",
	Minus = "Minus",
	Equal = "Equal",
	Enter = "Enter",
	Space = "Space",
	Period = "Period",
	Comma = "Comma",
	Slash = "Slash",
	Backslash = "Backslash",
	Semicolor = "Semicolon",
	Quote = "Quote",
	LeftBracket = "BracketLeft",
	RightBracket = "BracketRight",
	Tab = "Tab",

	ArrowLeft = "ArrowLeft",
	ArrowUp = "ArrowUp",
	ArrowDown = "ArrowDown",
	ArrowRight = "ArrowRight",


	LeftShift = "ShiftLeft",
	LeftControl = "ControlLeft",
	LeftAlt = "AltLeft",
	RightShift = "ShiftRight",
	RightControl = "ControlRight",
	RightAlt = "AltRight",
}